# Generated by Django 3.1.4 on 2023-05-24 06:50

from django.db import migrations, models
import single_data_deduplication.models


class Migration(migrations.Migration):

    dependencies = [
        ('single_data_deduplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diffclum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='去重字段', max_length=255, verbose_name='去重字段')),
            ],
            options={
                'verbose_name': '去重字段',
                'verbose_name_plural': '去重字段',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Origclum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='原始字段', max_length=255, verbose_name='原始字段')),
            ],
            options={
                'verbose_name': '原始字段',
                'verbose_name_plural': '原始字段',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='deduplication',
            name='comparative_data',
        ),
        migrations.AddField(
            model_name='deduplication',
            name='errorlog',
            field=models.TextField(default='Nul'),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='out_data',
            field=models.FileField(blank=True, help_text='去重后的数据', null=True, upload_to=single_data_deduplication.models.user_directory_path, verbose_name='去重后的数据'),
        ),
        migrations.AddField(
            model_name='deduplication',
            name='DiffData',
            field=models.ManyToManyField(to='single_data_deduplication.Diffclum'),
        ),
        migrations.AddField(
            model_name='deduplication',
            name='origdata',
            field=models.ManyToManyField(to='single_data_deduplication.Origclum'),
        ),
    ]
