# Generated by Django 3.1.4 on 2023-05-24 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_data_deduplication', '0002_auto_20230524_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deduplication',
            options={'ordering': ['-id'], 'verbose_name': 'task', 'verbose_name_plural': 'task'},
        ),
    ]
