# Generated by Django 3.1.4 on 2023-05-19 14:09

import data_deduplication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiffData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='去重数据name', max_length=255, verbose_name='去重数据name')),
                ('comparative_data', models.FileField(help_text='去重数据', upload_to=data_deduplication.models.user_directory_path, verbose_name='去重数据')),
            ],
            options={
                'verbose_name': '去重数据',
                'verbose_name_plural': '去重数据',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Origdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='原始数据name', max_length=255, verbose_name='原始数据name')),
                ('raw_data', models.FileField(help_text='原始数据', upload_to=data_deduplication.models.user_directory_path, verbose_name='原始数据')),
            ],
            options={
                'verbose_name': '原始数据',
                'verbose_name_plural': '原始数据',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Deduplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.FileField(help_text='taskname', upload_to='', verbose_name='taskname')),
                ('status', models.BooleanField(default=False, help_text='状态', verbose_name='状态')),
                ('error', models.BooleanField(default=False, help_text='错误', verbose_name='错误')),
                ('task_done', models.BooleanField(default=False, help_text='任务', verbose_name='任务')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('DiffData', models.ManyToManyField(to='data_deduplication.DiffData')),
                ('doituser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('origfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_deduplication.origdata')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'task',
                'ordering': ['-id'],
            },
        ),
    ]
