# Generated by Django 3.1.4 on 2023-05-09 13:09

import data_deduplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(help_text='任务名称', max_length=255, verbose_name='任务名称')),
                ('raw_data', models.FileField(help_text='原始数据', upload_to=data_deduplication.models.user_directory_path, verbose_name='原始数据')),
                ('comparative_data', models.FileField(help_text='去重数据', upload_to=data_deduplication.models.user_directory_path, verbose_name='去重数据')),
                ('out_data', models.FileField(blank=True, help_text='去重hou数据', null=True, upload_to=data_deduplication.models.user_directory_path, verbose_name='去重hou数据')),
                ('status', models.BooleanField(default=False, help_text='状态', verbose_name='状态')),
                ('error', models.BooleanField(default=False, help_text='错误', verbose_name='错误')),
                ('task_done', models.BooleanField(default=False, help_text='错误', verbose_name='错误')),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数据去重',
                'verbose_name_plural': '数据去重',
                'ordering': ['-id'],
            },
        ),
    ]
