# Generated by Django 3.1.4 on 2023-05-11 07:08

import data_deduplication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_deduplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduplication',
            name='doituser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deduplication',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='out_data',
            field=models.FileField(blank=True, help_text='去重的数据', null=True, upload_to=data_deduplication.models.user_directory_path, verbose_name='去重的数据'),
        ),
        migrations.AlterField(
            model_name='deduplication',
            name='task_done',
            field=models.BooleanField(default=False, help_text='任务', verbose_name='任务'),
        ),
    ]
