# Generated by Django 3.1.4 on 2023-05-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deduplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduplication',
            name='taskname',
            field=models.CharField(help_text='taskname', max_length=255, verbose_name='taskname'),
        ),
    ]
