# Generated by Django 3.1.4 on 2023-05-19 14:25

import data_deduplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deduplication', '0002_auto_20230519_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduplication',
            name='out_data',
            field=models.FileField(blank=True, help_text='去重的数据', null=True, upload_to=data_deduplication.models.user_directory_path, verbose_name='去重的数据'),
        ),
    ]
