# Generated by Django 3.1.4 on 2023-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deduplication', '0003_deduplication_out_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduplication',
            name='origfile',
        ),
        migrations.AddField(
            model_name='deduplication',
            name='origdata',
            field=models.ManyToManyField(to='data_deduplication.Origdata'),
        ),
    ]
