# Generated by Django 3.1.4 on 2023-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_deduplication', '0004_auto_20230519_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduplication',
            name='errorlog',
            field=models.TextField(default='Nul'),
        ),
    ]
